<a href="https://colab.research.google.com/github/lekhana04-ds/Data-science-portfolio/blob/main/DL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
a=tf.constant(4)
b=tf.constant(5)
result=tf.add(a,b)
print(result.numpy())

9


In [ ]:
import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
shape = tensor.shape
print('tensor:', tensor)
print('Tensor shape:', shape)


tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor shape: (2, 3)


In [ ]:
import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
size = tf.size(tensor)
print("Tensor size:", size)

Tensor size: tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
c = tf.constant([1, 2, 3])
print("Constant Tensor:", c.numpy())

v = tf.Variable([1, 2, 3])
print("Variable Tensor:", v.numpy())

z = tf.zeros([2, 3])
print("Zeros Tensor:/n", z.numpy())

o = tf.ones([2, 2])
print("Ones Tensor:/n", o.numpy())

rn = tf.random.normal([2, 3], mean=0.0, stddev=1.0)
print("Random Normal Tensor:\n", rn.numpy())

ru = tf.random.uniform([2, 2], minval=0, maxval=1.0)
print("random Uniform Tensor:\n", ru.numpy())

Constant Tensor: [1 2 3]
Variable Tensor: [1 2 3]
Zeros Tensor:/n [[0. 0. 0.]
 [0. 0. 0.]]
Ones Tensor:/n [[1. 1.]
 [1. 1.]]
Random Normal Tensor:
 [[-0.5574986  -0.6840161   0.20566742]
 [ 0.34328344 -0.31749395 -0.2977996 ]]
random Uniform Tensor:
 [[0.985095   0.9101355 ]
 [0.71991336 0.8467231 ]]


In [ ]:
import tensorflow as tf
print("Add:", tf.add(5, 3).numpy())
print("Subtract:", tf.subtract(10, 4).numpy())
print("Multiply:", tf.multiply([1, 2], [3, 4]).numpy())
print("Divide:", tf.divide([10, 20], [2, 5]).numpy())

a = tf.constant([[1, 2]])
b = tf.constant([[3],
                 [4]])
print("Matrix Multiplication:", tf.matmul(a, b).numpy())
print("Reduce Sum:", tf.reduce_sum([1, 2, 3]).numpy())
print("Reduce Mean:", tf.reduce_mean([2.0, 4.0, 6.0]).numpy())

Add: 8
Subtract: 6
Multiply: [3 8]
Divide: [5. 4.]
Matrix Multiplication: [[11]]
Reduce Sum: 6
Reduce Mean: 4.0
